"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-1d(mo$-g#$shq%j4g&6sb8my2vzet97jmsn(ajtrfq@nhooyop')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    # Local apps
    'mpesa.apps.MpesaConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000').split(',')

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': os.getenv('LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'mpesa': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Safaricom Daraja API Settings
DARAJA = {
    'ENVIRONMENT': os.getenv('DARAJA_ENVIRONMENT', 'sandbox'),
    'CONSUMER_KEY': os.getenv('DARAJA_CONSUMER_KEY', ''),
    'CONSUMER_SECRET': os.getenv('DARAJA_CONSUMER_SECRET', ''),
    'SHORTCODE': os.getenv('DARAJA_SHORTCODE', ''),
    'TILL_NUMBER': os.getenv('DARAJA_TILL_NUMBER', ''),
    'PAYBILL': os.getenv('DARAJA_PAYBILL', ''),
    'INITIATOR_NAME': os.getenv('DARAJA_INITIATOR_NAME', ''),
    'INITIATOR_PASSWORD': os.getenv('DARAJA_INITIATOR_PASSWORD', ''),
    'PASSKEY': os.getenv('DARAJA_PASSKEY', ''),
    'CALLBACK_BASE_URL': os.getenv('DARAJA_CALLBACK_BASE_URL', 'http://localhost:8000'),
    'STK_CALLBACK_URL': os.getenv('DARAJA_STK_CALLBACK_URL', ''),
    'B2C_CALLBACK_URL': os.getenv('DARAJA_B2C_CALLBACK_URL', ''),
    'B2B_CALLBACK_URL': os.getenv('DARAJA_B2B_CALLBACK_URL', ''),
    'C2B_VALIDATION_URL': os.getenv('DARAJA_C2B_VALIDATION_URL', ''),
    'C2B_CONFIRMATION_URL': os.getenv('DARAJA_C2B_CONFIRMATION_URL', ''),
    'REVERSAL_CALLBACK_URL': os.getenv('DARAJA_REVERSAL_CALLBACK_URL', ''),
    'TRANSACTION_STATUS_CALLBACK_URL': os.getenv('DARAJA_TRANSACTION_STATUS_CALLBACK_URL', ''),
    'ACCOUNT_BALANCE_CALLBACK_URL': os.getenv('DARAJA_ACCOUNT_BALANCE_CALLBACK_URL', ''),
    'TIMEOUT': int(os.getenv('DARAJA_TIMEOUT', '30')),
    'TOKEN_CACHE_DURATION': int(os.getenv('DARAJA_TOKEN_CACHE_DURATION', '3500')),
}
STATIC_URL = 'static/'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Safaricom Daraja Django API',
    'DESCRIPTION': '''
    Complete M-Pesa integration API for Django applications.
    
    This API provides endpoints for:
    - STK Push (Lipa na M-Pesa Online) payments
    - Transaction status queries
    - C2B (Customer to Business) registration
    - Callback handling for all M-Pesa operations
    
    ## Authentication
    Currently using AllowAny permissions for development. 
    In production, implement proper authentication.
    
    ## M-Pesa API Documentation
    For more information about M-Pesa APIs, visit:
    https://developer.safaricom.co.ke/
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/',
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
    },
    'TAGS': [
        {'name': 'M-Pesa Payments', 'description': 'STK Push and payment operations'},
        {'name': 'M-Pesa Transactions', 'description': 'Transaction status and history'},
        {'name': 'M-Pesa Configuration', 'description': 'C2B URL registration and setup'},
    ],
    'CONTACT': {
        'name': 'API Support',
        'email': 'support@yourdomain.com',
    },
}
