# Generated by Django 6.0 on 2025-12-25 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('originator_conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(choices=[('STK_PUSH', 'STK Push / Lipa Na M-Pesa'), ('B2C', 'Business to Customer'), ('B2B', 'Business to Business'), ('C2B', 'Customer to Business'), ('REVERSAL', 'Transaction Reversal'), ('TRANSACTION_STATUS', 'Transaction Status Query'), ('ACCOUNT_BALANCE', 'Account Balance Query'), ('B2B_EXPRESS', 'B2B Express Checkout'), ('TAX_REMITTANCE', 'Tax Remittance')], max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('account_reference', models.CharField(blank=True, max_length=100)),
                ('transaction_desc', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('callback_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='mpesa_trans_created_e5028a_idx'), models.Index(fields=['status', '-created_at'], name='mpesa_trans_status_b5c096_idx'), models.Index(fields=['transaction_type', '-created_at'], name='mpesa_trans_transac_a3d50e_idx')],
            },
        ),
        migrations.CreateModel(
            name='STKPushTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=100, unique=True)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_reference', models.CharField(max_length=100)),
                ('transaction_desc', models.CharField(blank=True, max_length=255)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stk_push_details', to='mpesa.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReversalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator_conversation_id', models.CharField(max_length=100)),
                ('conversation_id', models.CharField(blank=True, max_length=100)),
                ('original_transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiver_party', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('occasion', models.CharField(blank=True, max_length=255)),
                ('reversed_transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reversal_details', to='mpesa.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='C2BTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=100, unique=True)),
                ('trans_time', models.CharField(max_length=20)),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_short_code', models.CharField(max_length=20)),
                ('bill_ref_number', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('msisdn', models.CharField(max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('org_account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='c2b_details', to='mpesa.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='B2CTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator_conversation_id', models.CharField(max_length=100)),
                ('conversation_id', models.CharField(blank=True, max_length=100)),
                ('command_id', models.CharField(choices=[('SalaryPayment', 'Salary Payment'), ('BusinessPayment', 'Business Payment'), ('PromotionPayment', 'Promotion Payment')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('party_a', models.CharField(max_length=20)),
                ('party_b', models.CharField(max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('occasion', models.CharField(blank=True, max_length=255)),
                ('mpesa_transaction_id', models.CharField(blank=True, max_length=100)),
                ('transaction_receipt', models.CharField(blank=True, max_length=100)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('working_account_funds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utility_account_funds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('b2c_charges_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2c_details', to='mpesa.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_type', models.CharField(choices=[('STK_PUSH', 'STK Push Callback'), ('B2C', 'B2C Result'), ('B2B', 'B2B Result'), ('C2B_VALIDATION', 'C2B Validation'), ('C2B_CONFIRMATION', 'C2B Confirmation'), ('REVERSAL', 'Reversal Result'), ('TRANSACTION_STATUS', 'Transaction Status'), ('ACCOUNT_BALANCE', 'Account Balance')], max_length=50)),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_logs', to='mpesa.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='mpesa_callb_created_012f84_idx'), models.Index(fields=['callback_type', '-created_at'], name='mpesa_callb_callbac_57eaf0_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='mpesa.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='mpesa_apire_created_1616fb_idx'), models.Index(fields=['endpoint', '-created_at'], name='mpesa_apire_endpoin_017da2_idx'), models.Index(fields=['status_code', '-created_at'], name='mpesa_apire_status__3dbed0_idx')],
            },
        ),
    ]
