# Generated by Django 6.0 on 2026-01-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('originator_conversation_id', models.CharField(db_index=True, max_length=100)),
                ('result_code', models.CharField(max_length=10)),
                ('result_desc', models.TextField()),
                ('working_account_available', models.DecimalField(blank=True, decimal_places=2, help_text='Working account available funds', max_digits=15, null=True)),
                ('working_account_uncleared', models.DecimalField(blank=True, decimal_places=2, help_text='Working account uncleared funds', max_digits=15, null=True)),
                ('working_account_reserved', models.DecimalField(blank=True, decimal_places=2, help_text='Working account reserved funds', max_digits=15, null=True)),
                ('charges_paid_available', models.DecimalField(blank=True, decimal_places=2, help_text='Charges paid account available funds', max_digits=15, null=True)),
                ('charges_paid_uncleared', models.DecimalField(blank=True, decimal_places=2, help_text='Charges paid account uncleared funds', max_digits=15, null=True)),
                ('charges_paid_reserved', models.DecimalField(blank=True, decimal_places=2, help_text='Charges paid account reserved funds', max_digits=15, null=True)),
                ('utility_account_available', models.DecimalField(blank=True, decimal_places=2, help_text='Utility account available funds', max_digits=15, null=True)),
                ('utility_account_uncleared', models.DecimalField(blank=True, decimal_places=2, help_text='Utility account uncleared funds', max_digits=15, null=True)),
                ('utility_account_reserved', models.DecimalField(blank=True, decimal_places=2, help_text='Utility account reserved funds', max_digits=15, null=True)),
                ('organization_settlement_available', models.DecimalField(blank=True, decimal_places=2, help_text='Organization settlement account available funds', max_digits=15, null=True)),
                ('raw_result_parameters', models.JSONField(blank=True, help_text='Raw result parameters from M-PESA callback', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Account Balance',
                'verbose_name_plural': 'Account Balances',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='mpesa_accou_created_b6d261_idx'), models.Index(fields=['conversation_id'], name='mpesa_accou_convers_0c97a2_idx'), models.Index(fields=['result_code', '-created_at'], name='mpesa_accou_result__474cd7_idx')],
            },
        ),
    ]
